---
  - name: installing ansible application requiriments
    yum: name={{ item }} state=installed
    #state: latest
    with_items:
    - centos-release-openstack-newton

  - name: Updating YUM 
    command: yum update -y

  - name: installing ansible application requiriments
    yum: name={{ item }} state=installed
    #state: latest
    with_items:    
    - openstack-packstack

  - name: stop services and disabling
    service: name={{ item }} state=stopped enabled=no
    with_items:  
    - firewalld
    - NetworkManager  
    ignore_errors: true

  - name: starting services and enabling
    service: name={{ item }} state=restarted enabled=yes
    with_items:  
    - network
    ignore_errors: true

  - name: Installing Openstack Newton ( please, wait.)
    command: packstack --allinone
    register: update
  - debug: var=update.stdout_lines



